#!/usr/bin/env sh

# Determine file path(s) to delete
selection_file=${NNN_SEL:-${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.selection}
hovered_file="$1"

# Function to clear nnn selection
clear_selection() {
	if [ -p "$NNN_PIPE" ]; then
		printf "-" >"$NNN_PIPE"
	fi
}

# Check for empty selection file
if [ -s "$selection_file" ]; then
	# Remove null characters for printing files to be deleted
	selected_files=$(tr '\0' '\n' <"$selection_file")
	# Prompt for confirmation to delete selected files
	printf "%s\nDo you wanna permanently remove those files? [y-n] " "$selected_files"
	read -r user_response_selection
else
	# Prompt for confirmation to delete hovered file
	printf "rm -rf %s? [y-n] " "$hovered_file"
	read -r user_response_hovered
fi

# Handle deletion if user confirms
if [ "$user_response_selection" = "y" ]; then
	# Delete selected files
	xargs -0 rm -rf <"$selection_file"
	clear_selection
elif [ "$user_response_hovered" = "y" ]; then
	# Delete hovered file
	rm -rf "$hovered_file"
	clear_selection
else
	echo "Please select a valid response" 1>&2
  exit 1
fi
