require('options')
require('keymaps')
require('plugins')
require('TokyoNight-conf')
-- require('nord-conf')
require('telescope-conf')
require('bufferline-conf')
require('treesitter-conf')
require('lualine-conf')
require('LSPConfig')
require('Nvimcmp-conf')

