require('options')
require('keymaps')
require('plugins')
require('gruvbox-conf')
-- require('nord-conf')
-- require("Doom-one-conf")
require('treesitter-conf')
require('telescope-conf')
require('bufferline-conf')
require('lualine-conf')
require('LSPConfig')
require('Nvimcmp-conf')
