filetype plugin indent on

set termencoding=utf-8
set encoding=utf-8

" use 4 spaces for tabs
set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4
set shiftround

set backspace =indent,eol,start
set hidden
set laststatus=2

" Set linenumbers
set number
set relativenumber
set wrap

" Highlight searching
set incsearch
set showmatch
set hlsearch
set ignorecase
set smartcase
set autoread " autoread files
set mouse=a " use mouse for scroll or window size
set hidden                      " Needed to keep multiple buffers open

if has('persistent_undo')         "check if your vim version supports
  set undodir=$HOME/.vim/undo     "directory where the undo files will be stored
  set undofile                    "turn on the feature
endif

set noswapfile
set viminfo='10,<100,:100,%,n~/.vim/.viminfo
set t_Co=256                    " Set if term supports 256 colors.
set wildmenu
set cursorline
syntax enable
nnoremap <C-l> :nohl<cr>
