require('options')
require('keymaps')
require('plugins')
require('nord-conf')
require('telescope-conf')
require('bufferline-conf')
require('treesitter-conf')
require('lualine-conf')
-- require('MyStatusline')

